import { useState } from 'react';
import { Clock, ChevronDown, ChevronUp } from 'lucide-react';
import ScoreGauge from './ScoreGauge.jsx';
import EvidenceCard from './EvidenceCard.jsx';
import KPICard from './KPICard.jsx';
import GapItem from './GapItem.jsx';
import FollowUpQuestion from './FollowUpQuestion.jsx';

const TAB_CONFIG = [
  { key: 'evidence', label: 'Evidence', count: (d) => d.extractedEvidence?.length },
  { key: 'kpi', label: 'KPI Mapping', count: (d) => d.kpiMapping?.length },
  { key: 'gaps', label: 'Gaps', count: (d) => d.gapAnalysis?.length },
  { key: 'questions', label: 'Follow-up Qs', count: (d) => d.followUpQuestions?.length },
];

export default function AnalysisResult({ data }) {
  const [activeTab, setActiveTab] = useState('evidence');
  const [showJustification, setShowJustification] = useState(false);

  if (!data) return null;

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Disclaimer banner */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 flex items-start gap-2">
        <span className="text-amber-600 text-sm">⚠️</span>
        <p className="text-sm text-amber-800">
          <strong>Draft output.</strong> This analysis is generated by AI and may contain errors. Use it as a starting point for your own assessment — not as a final verdict.
        </p>
      </div>

      {/* Score card */}
      <div className="card p-6">
        <div className="section-label mb-4">Rubric Score</div>
        <ScoreGauge score={data.rubricScore?.score} />

        {data.rubricScore?.justification && (
          <div className="mt-4">
            <button
              onClick={() => setShowJustification(!showJustification)}
              className="flex items-center gap-1.5 text-sm text-ink-500 hover:text-ink-700 transition-colors"
            >
              {showJustification ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
              {showJustification ? 'Hide' : 'Show'} justification
            </button>
            {showJustification && (
              <p className="mt-3 text-sm text-ink-600 leading-relaxed bg-ink-50 rounded-lg p-4 border border-ink-200 animate-slide-up">
                {data.rubricScore.justification}
              </p>
            )}
          </div>
        )}

        {data.processingTimeMs && (
          <div className="mt-4 flex items-center gap-1.5 text-xs text-ink-400">
            <Clock className="w-3 h-3" />
            Processed in {(data.processingTimeMs / 1000).toFixed(1)}s · Model: {data.modelUsed || 'llama3.2'}
          </div>
        )}
      </div>

      {/* Tabbed sections */}
      <div className="card overflow-hidden">
        <div className="border-b border-ink-200 flex overflow-x-auto">
          {TAB_CONFIG.map((tab) => {
            const count = tab.count(data);
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={`px-5 py-3.5 text-sm font-medium whitespace-nowrap border-b-2 transition-colors flex items-center gap-2 ${
                  activeTab === tab.key
                    ? 'border-ink-900 text-ink-900'
                    : 'border-transparent text-ink-500 hover:text-ink-700'
                }`}
              >
                {tab.label}
                {count != null && (
                  <span className="text-xs bg-ink-100 text-ink-600 rounded-full w-5 h-5 flex items-center justify-center">
                    {count}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        <div className="p-5 space-y-3">
          {activeTab === 'evidence' && (
            <>
              {data.extractedEvidence?.length > 0 ? (
                data.extractedEvidence.map((item, i) => <EvidenceCard key={i} item={item} />)
              ) : (
                <EmptyState text="No evidence extracted." />
              )}
            </>
          )}

          {activeTab === 'kpi' && (
            <>
              {data.kpiMapping?.length > 0 ? (
                data.kpiMapping.map((item, i) => <KPICard key={i} item={item} />)
              ) : (
                <EmptyState text="No KPIs identified." />
              )}
            </>
          )}

          {activeTab === 'gaps' && (
            <>
              {data.gapAnalysis?.length > 0 ? (
                data.gapAnalysis.map((item, i) => <GapItem key={i} item={item} />)
              ) : (
                <EmptyState text="No gaps identified — the transcript was comprehensive." />
              )}
            </>
          )}

          {activeTab === 'questions' && (
            <div className="space-y-4">
              {data.followUpQuestions?.length > 0 ? (
                data.followUpQuestions.map((item, i) => <FollowUpQuestion key={i} item={item} index={i} />)
              ) : (
                <EmptyState text="No follow-up questions generated." />
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function EmptyState({ text }) {
  return (
    <p className="text-sm text-ink-400 py-6 text-center">{text}</p>
  );
}
